version: 1.2
workflows:
  - name: RNA_aggregate
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_aggregate.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - main
  - name: RNA_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_pipeline.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - main
  - name: rsem_depmap
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rsem_depmap.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - main
        - rsem_confidence_interval_calculation
